name: Monthly GH Actions Update Check

on:
  schedule:
    - cron: "0 10 1 * *" # Once per month
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: ".nvmrc"

      - run: npm install -g actions-up

      - run: |
          if actions-up --dry-run | grep -q "â†’"; then
            echo "Updates available! Run 'npx actions-up' to update."
            exit 1
          fi
