name: Monthly GH Actions Update Check

on:
  schedule:
    - cron: "0 10 1 * *" # Once per month
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: ".nvmrc"

      - run: pnpm install actions-up@1.6.0

      - run: |
          if npx actions-up --dry-run | grep -q "â†’"; then
            echo "Updates available! Run 'npx actions-up' to update."
            exit 1
          fi
